version: "3.8"

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        image: mavis-app:latest
        container_name: MAVIS_App
        working_dir: /app
        ports:
            - "8000:8000"
            - "8001:8001"
            - "3000:3000"
        volumes:
            - .:/app
        command: python manage.py runserver 0.0.0.0:8000 -l 6
        environment:
            - DEBUG=1
            - DJANGO_ALLOWED_HOSTS=localhost 127.0.0.1
