version: '3.8'

services:
  app:
    build: .
    container_name: MAVIS_App
    working_dir: /app
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    command: ["python", "manage.py", "runserver", "-l", "3"]