# Generated by Django 5.1.3 on 2025-02-03 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="image",
            name="image_hash",
            field=models.TextField(),
        ),
    ]
