# Generated by Django 5.1.7 on 2025-03-21 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="image",
            name="mavis_cert",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="image",
            name="mavis_cert_hash",
            field=models.TextField(null=True),
        ),
    ]
