# Generated by Django 5.1.3 on 2025-02-04 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0002_alter_image_image_hash"),
    ]

    operations = [
        migrations.AddField(
            model_name="image",
            name="original_image_hash",
            field=models.TextField(null=True),
        ),
    ]
