# Generated by Django 5.1.7 on 2025-03-20 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0003_image_original_image_hash"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="devicekeys",
            name="private_key",
        ),
        migrations.RemoveField(
            model_name="devicekeys",
            name="user",
        ),
        migrations.AddField(
            model_name="devicekeys",
            name="uuid",
            field=models.TextField(default=None),
        ),
    ]
