# Generated by Django 5.1.7 on 2025-03-20 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0004_remove_devicekeys_private_key_remove_devicekeys_user_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="devicekeys",
            name="uuid",
            field=models.TextField(default="None"),
        ),
    ]
